import { Resend } from 'resend'
import { marked } from 'marked'

if (!process.env.RESEND_API_KEY) {
  throw new Error('Missing RESEND_API_KEY environment variable')
}

export const resend = new Resend(process.env.RESEND_API_KEY)

export async function sendEmail(
  recipients: string[],
  summary: string,
  subject: string = 'Meeting Summary'
) {
  try {
    // Convert Markdown (with bold, italic, lists, etc.) → HTML
    const summaryHtml = marked.parse(summary)

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
              line-height: 1.6;
              color: #1f2937;
              max-width: 650px;
              margin: 0 auto;
              background: #f3f4f6;
            }
            .container {
              background: #ffffff;
              border-radius: 12px;
              box-shadow: 0 4px 12px rgba(0,0,0,0.08);
              margin: 30px auto;
              overflow: hidden;
            }
            .header {
              background: linear-gradient(135deg, #6b21a8 0%, #9333ea 100%);
              color: white;
              padding: 28px 20px;
              text-align: center;
            }
            .header h1 {
              margin: 0;
              font-size: 26px;
              font-weight: 600;
            }
            .content {
              padding: 28px 32px;
              background: #fafafa;
            }
            h2 {
              color: #6b21a8;
              font-size: 18px;
              margin-bottom: 16px;
            }
            .summary {
              background: #ffffff;
              padding: 18px 20px;
              border-left: 4px solid #9333ea;
              border-radius: 6px;
              font-size: 15px;
              line-height: 1.6;
            }
            .summary strong {
              font-weight: bold;
              color: #6b21a8;
            }
            .summary em {
              font-style: italic;
              color: #9333ea;
            }
            ul, ol {
              margin: 10px 0 10px 20px;
            }
            li {
              margin-bottom: 6px;
            }
            .footer {
              text-align: center;
              padding: 20px;
              color: #6b7280;
              font-size: 12px;
              border-top: 1px solid #e5e7eb;
              background: #fafafa;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>📝 Meeting Summary</h1>
              <p>Generated by AI Meeting Notes Summarizer</p>
            </div>
            <div class="content">
              <h2>Summary Details</h2>
              <div class="summary">
                ${summaryHtml}
              </div>
            </div>
            <div class="footer">
              <p>This summary was automatically generated using AI technology.</p>
              <p>© 2024 AI Meeting Notes Summarizer. All rights reserved.</p>
            </div>
          </div>
        </body>
      </html>
    `

    const data = await resend.emails.send({
      from: 'Meetsummary@sheig.shop',
      to: recipients,
      subject,
      html: htmlContent,
      text: summary, // keep plain text as fallback
    })

    return { success: true, data }
  } catch (error) {
    console.error('Error sending email:', error)
    throw error
  }
}
