import { Resend } from 'resend'

if (!process.env.RESEND_API_KEY) {
  throw new Error('Missing RESEND_API_KEY environment variable')
}

export const resend = new Resend(process.env.RESEND_API_KEY)

export async function sendEmail(
  recipients: string[],
  summary: string,
  subject: string = 'Meeting Summary'
) {
  try {
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 600px;
              margin: 0 auto;
              padding: 20px;
            }
            .header {
              background: linear-gradient(135deg, #6b21a8 0%, #9333ea 100%);
              color: white;
              padding: 30px;
              border-radius: 10px 10px 0 0;
              text-align: center;
            }
            .content {
              background: #f9fafb;
              padding: 30px;
              border-radius: 0 0 10px 10px;
            }
            .summary {
              background: white;
              padding: 20px;
              border-radius: 8px;
              border-left: 4px solid #9333ea;
              margin: 20px 0;
            }
            .footer {
              text-align: center;
              margin-top: 30px;
              color: #666;
              font-size: 12px;
            }
            h1 {
              margin: 0;
              font-size: 24px;
            }
            h2 {
              color: #6b21a8;
              font-size: 18px;
              margin-top: 0;
            }
            ul, ol {
              margin: 10px 0;
              padding-left: 20px;
            }
            li {
              margin: 5px 0;
            }
            strong {
              color: #6b21a8;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>📝 Meeting Summary</h1>
            <p style="margin: 10px 0 0 0; opacity: 0.9;">Generated by AI Meeting Notes Summarizer</p>
          </div>
          <div class="content">
            <h2>Summary Details</h2>
            <div class="summary">
              ${summary.replace(/\n/g, '<br>')}
            </div>
            <div class="footer">
              <p>This summary was automatically generated using AI technology.</p>
              <p>© 2024 AI Meeting Notes Summarizer. All rights reserved.</p>
            </div>
          </div>
        </body>
      </html>
    `

    const data = await resend.emails.send({
      from: 'Meetsummary@sheig.shop',
      to: recipients,
      subject: subject,
      html: htmlContent,
      text: summary,
    })

    return { success: true, data }
  } catch (error) {
    console.error('Error sending email:', error)
    throw error
  }
}